### ISSUE TITLE
Motorbremswirkung scheint zu stark zu sein 

### ISSUE THREAD

**Issue by Horschde** [Achimobil/FS22_MB_Sprinter_3x_autoload#6]
Hallo Achimobil,

ich finde das der Sprinter beim "Gas" wegnehmen zu stark abbremst. Man braucht eigentlich keine Betriebsbremse, nur einfach das Gas wegnehmen. Ich habe mal eine Test gemacht mit Deinen beiden Versionen vom Sprinter und 2 anderen Fahrzeugen. Noch ein Sprinter (Mod nicht aus dem Modhub) und eine Pickup (Mod nicht aus dem Modhub). Wenn ich auf gleicher Höhe den Tempomat ausschalte, dann rollen die anderen 2 wesentlich weiter, bis Sie zum stehen kommen.
Vielleicht probierst Du es selbst nochmal aus und passt da ggf. was an. Du bist sicherlich selbst Autofahrer und weißt ja wie sich beim echten Fahrzeug die Verzögerung beim Gas wegnehmen auswirkt.

Danke für Dein Bemühen im Voraus
Mit freundlichen Grüßen vom Horschd 

![Farming Simulator 22 Screenshot 2023 08 23 - 18 57 41 94](https://github.com/Achimobil/FS22_MB_Sprinter_3x_autoload/assets/86984457/66378c30-9df7-4ee7-8730-d94fb5d66d49)
![Farming Simulator 22 Screenshot 2023 08 23 - 19 02 17 11](https://github.com/Achimobil/FS22_MB_Sprinter_3x_autoload/assets/86984457/7b47f701-b23a-4b5e-a12c-00dfa575b501)
![Farming Simulator 22 Screenshot 2023 08 23 - 19 03 21 57](https://github.com/Achimobil/FS22_MB_Sprinter_3x_autoload/assets/86984457/2a306182-afe2-4f52-bc99-1e6297bf5a77)

**Comment by Achimobil** [comment]
Ab Version 1.3.0.1 gefixed
