### ISSUE TITLE
Betitelung im F1 Menu des Ausladens beim Autoload vertauscht (links/rechts)

### ISSUE THREAD

**Issue by Mapela80** [Achimobil/FS22_MB_Sprinter_3x_autoload#9]
hallo guten morgen, 

ich hab entdeckt dass beim Sprinter links und rechts ausladen vertauscht ist im F1 Menu,  es ist die Version 1.4.0.0.

![image](https://github.com/user-attachments/assets/cd933a51-6dde-4ec9-8019-f39c8ec94035)

Grüße

Gemueseschaefchen/Mapela80

**Comment by Achimobil** [comment]
Fehler gefunden und korrigiert für das nächste Update
